/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 monkey.gltf 
Author: giyasudeen31 (https://sketchfab.com/giyasudeen31)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nft-monkey-eec322fcf2704337976f9b7bf29c0be1
Title: NFT Monkey
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/monkey.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.382}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.211, 3.554, 0.406]}
            rotation={[-3.047, 0.066, 2.652]}
            scale={3.06}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.cigarette}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.Material}
            />
          </group>
          <group
            position={[0.113, 3.946, 0.16]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.03}
          >
            <mesh
              geometry={nodes.Object_15.geometry}
              material={materials.Std_Eye_L}
            />
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials.Std_Cornea_L}
            />
          </group>
          <group position={[0, 2.598, -0.055]} scale={[0.377, 0.377, 0.418]}>
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials["Material.010"]}
            />
          </group>
          <group
            position={[-0.009, 3.926, 0.224]}
            rotation={[1.508, -Math.PI / 2, 0]}
            scale={0.103}
          >
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials.Metal}
            />
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials.Glass}
            />
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials.plastic}
            />
          </group>
          <group
            position={[0.304, 3.955, 0.211]}
            rotation={[0.031, -1.569, -1.631]}
            scale={0.103}
          >
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials.Metal}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials.plastic}
            />
          </group>
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.Body}
            position={[0, 3.676, 0.174]}
            scale={0.252}
          />
          <mesh
            geometry={nodes.mesh_2.geometry}
            material={materials.Ga_Skin_Body}
            position={[0, 3.519, 0.23]}
            scale={0.03}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.Std_Lower_Teeth}
            position={[0, 3.513, 0.264]}
            scale={[0.036, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.Std_Upper_Teeth}
            position={[0, 3.513, 0.264]}
            scale={[0.036, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Tail}
            position={[0, 1.89, -0.194]}
            scale={0.046}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials["Material.004"]}
            position={[0, 2.721, 0.082]}
            scale={[0.083, 0.316, 0.029]}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials["Material.005"]}
            position={[0, 2.462, 0.034]}
            scale={[0.093, 0.353, 0.032]}
          />
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials["Material.006"]}
            position={[0, 3.211, 0.002]}
            scale={[0.086, 0.326, 0.025]}
          />
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials["Material.008"]}
            position={[0, 1.387, 0]}
            scale={[0.382, 0.294, 0.364]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/monkey.gltf");
